#!/usr/bin/env python3

"""my cool lights"""

import random
import RPi.GPIO as GPIO
import time as t

pins  = [4,27,22,5,6,13,19,26]
default_speed= .1


GPIO.setmode(GPIO.BCM)
GPIO.setup(pins,GPIO.OUT)

def on(pin): GPIO.output(pin,GPIO.HIGH)

def off(pin): GPIO.output(pin,GPIO.LOW)

def slowon(list=pins,delay=1):
    for pin in list:
        on(pin)
        t.sleep(delay)

def slowoff(list=pins,delay=1):
    for pin in list:
        off(pin)
        t.sleep(delay)

def chase(count=1,delay=default_speed):
    for n in range(count):
        slowon(delay=delay)
        slowoff(delay=delay)

def updown(count=1,delay=.1):
    for n in range(count):
        slowon(delay=delay)
        slowoff(delay=delay,list=pins[::-1])

def bounce(count=1,delay=.1):
    for n in range(count):
        on(5)
        on(6)
        t.sleep(1)
        off(5)
        off(6)
        on(13)
        on(22)
        t.sleep(1)
        off(13)
        off(22)
        on(27)
        on(19)
        t.sleep(1)
        off(27)
        off(19)
        on(4)
        on(26)
        t.sleep(1)        
        off(4)
        off(26)

if __name__ == "__main__":
    while True:
        choices = [slowon(),slowoff(),chase(),updown(),bounce()]

        random.choice(choices)
        

        
