#!/usr/bin/env python3
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(6, GPIO.OUT)

while True:
        GPIO.output(6, GPIO.HIGH)
        time.sleep(1)
        GPIO.output(6, GPIO.LOW)
        time.sleep(1)
        GPIO.output(27, GPIO.HIGH)
        time.sleep(1)
        GPIO.output(27, GPIO.LOW)
        time.sleep(1)
        GPIO.output(22, GPIO.HIGH)
        time.sleep(1)
        GPIO.output(22, GPIO.LOW)
        time.sleep(1)
        GPIO.output(25, GPIO.HIGH)
        time.sleep(1)
        GPIO.output(25, GPIO.LOW)
        time.sleep(1)
        GPIO.output(5, GPIO.HIGH)
        sleep(1)
        GPIO.output(5, GPIO.HIGH)
        time.sleep(1)
GPIO.cleanup()
